image:
  repository: similarweb/statusbay
  tag: dev
  pullPolicy: Always

database:
  type: external
  host: statusier.production.us-east-1.int.similarweb.io
  port: 3306
  username: root
  password: ee7caef4ohRopheu
  schema: statusbay


redis:
  type: internal

  host: 127.0.0.1
  port: 6379
  password: 
  db: 0

  internal:
    image:
      repository: redis
      tag: 5.0.7
      pullPolicy: IfNotPresent
    resources:
     requests:
       memory: 256Mi
       cpu: 100m
    persistence:
      persistentVolumeClaim:      
        accessMode: ReadWriteOnce
        storageClass: "-" 
        size: 1Gi

ingress:
  api:
    annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/ingress.class: "nginx-pe-internal-nginx-ingress-controller"
    host: api.statusbay.io
  ui:
    annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/ingress.class: "nginx-pe-internal-nginx-ingress-controller"
    host: demo.statusbay.io

service:
  api:
    type: ClusterIP
    annotations: {}
    externalPort: 80
  ui:
    type: ClusterIP
    annotations: {}
    externalPort: 80    

rbac:
  create: true

serviceAccount:
  create: true
  name: 

ui:
  create: true
  replicas: 3
  annotations: {}
  
  image:
    repository: similarweb/statusbay-ui
    tag: dev
    pullPolicy: Always
  
  environmentVars:
    GELF_ADDRESS: 127.0.0.1
    LOG_LEVEL: INFO
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

api:
  create: true
  replicas: 2
  annotations: {}
  application:    
    log:
      level: INFO
      # gelf_address: 127.0.0.1
    metrics:
      datadog:
        api_key: 5b490730119a748844d8f8a4db1efc99
        app_key: 8d67d6fff061aaec756ebee081dffc7f64d7a2fc
        cache_cleanup_interval: 1m
        cache_expiration: 3m      
      #   address: http://prometheus-url.domain:9090
    alerts:
      statuscake:
        endpoint: https://app.statuscake.com/API
        username: SimilarWeb
        api_key: HWkXI34axJ97qyfj8CQPnEGFpR5YTO
     
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

watcher:
  kubernetes:
    create: false
    annotations: {}
    application:
      cluster_name: default
      log:
        level: INFO
        # gelf_address: 127.0.0.1
      applies:
        save_interval: 2s
        max_apply_time: 10m
        check_finish_delay: 5s
        collect_data_after_apply_finish: 10s
      slack:
        token: xoxb-3292636427-955715945458-bVCyjhTQpb0BQjxiEpvnpNdO
        default_channels:
          - '#elad_test'
    resources:
      requests:
        cpu: 100m
        memory: 128Mi



