{{- if (.Values.serviceAccount.create) (.Values.watcher.kubernetes.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "statusbay.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "statusbay.labels" . | indent 4 }}
  annotations:
{{ include "statusbay.annotations" . | indent 4 }}
{{- end -}}
