{{- if .Values.ui.create }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "statusbay.fullname" . }}-ui
  labels:
{{ include "statusbay.labels" . | indent 4 }}
  annotations:
{{- if .Values.ingress.ui.annotations }}
{{ toYaml .Values.ingress.ui.annotations | indent 4 }}
{{- end }}
{{ include "statusbay.annotations" . | indent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.ui.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "statusbay.fullname" . }}-ui
              servicePort: {{ .Values.service.ui.externalPort }}
{{- end -}}