{{- if .Values.ui.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "statusbay.fullname" . }}-ui
  labels:
{{ include "statusbay.labels" . | indent 4 }}
  annotations:
{{- if .Values.ingress.ui.annotations }}
{{ toYaml .Values.ingress.ui.annotations | indent 4 }}
{{- end }}
{{ include "statusbay.annotations" . | indent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.ui.host }}
      http:
        paths:
          - path: {{ .Values.ingress.ui.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "statusbay.fullname" . }}-ui
                port:
                  number: {{ .Values.service.ui.externalPort }}
{{- if .Values.ingress.ui.use_tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.ui.host }}
{{- end }}
{{- end -}}
